apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-app-deployment-rolling-update
  labels:
    app: mlflow-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: mlflow-app
  template:
    metadata:
      name: mlflow-app
      labels:
        app: mlflow-app
    spec:
      containers:
        - name: mlflow-app
          image: abogovski/mlops-hw2:v2
          ports:
            - containerPort: 8000
