apiVersion: v1
kind: Pod
metadata:
  name: mlflow-app
spec:
  containers:
  - name: mlflow-app
    image: abogovski/mlops-hw2:v2
    ports:
      - containerPort: 8000
    livenessProbe:
      httpGet:
        path: /alive
        port: 8000
      initialDelaySeconds: 40
    readinessProbe:
      httpGet:
        path: /ready
        port: 8000
